version: '3.8'

services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8586:8586"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://products_db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - INVENTORY_SERVICE_URL=http://inventory-service:8587/inventory
    depends_on:
      - products_db
      - inventory-service
    networks:
      - backend

  products_db:
    image: postgres:15
    container_name: products_db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8587:8587"
    environment:
      - MONGODB_URI=mongodb+srv://<username>:<password>@<your-cluster>.mongodb.net/inventory?retryWrites=true&w=majority
    networks:
      - backend

networks:
  backend:
    driver: bridge
