version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8586:8586"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://products_db:5432/products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      INVENTORY_SERVICE_URL: http://inventory-service:8587/api/inventory/
    depends_on:
      - products_db
    networks:
      - micro-net

  products_db:
    image: postgres:15
    container_name: products_db
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - micro-net

networks:
  micro-net:
    external: true
