version: '3.8'

services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8587:8587"
    environment:
      - MONGODB_URI=mongodb+srv://<username>:<password>@<your-cluster>.mongodb.net/inventory?retryWrites=true&w=majority
    networks:
      - backend

networks:
  backend:
    driver: bridge
